Updated scanner.yml

diff --git a/.github/workflows/scanner.yml b/.github/workflows/scanner.yml
--- a/.github/workflows/scanner.yml
+++ b/.github/workflows/scanner.yml
@@ -24,6 +24,8 @@ jobs:
           wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
           echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
           sudo apt-get update
+          # Install trivy
+          sudo apt-get install trivy  
 
       # TASK/TODO: 
       # Build this step in the workflow. Refer to the linked document in the README for more details
@@ -32,5 +34,14 @@ jobs:
 
       - name: View issue information
         run: |
-          echo "Issue title: ${{ github.event.issue.title }}"
-          echo "Issue body: ${{ github.event.issue.body }}"
+          echo "${{ github.event.issue.body }}" | tr -d "[]" | tr -s "," "\n" | tac > newscan.txt
+          input=newscan.txt
+
+          while IFS= read -r image
+          do
+                  trivy image --security-checks vuln --quiet --exit-code 1 "$image" | tail -n 1
+                  status=$(echo $?)
+                  if [ "$status" -eq 0 ]; then safety="SAFE"; else safety="UNSAFE"; fi
+                  echo "\"image\": \"$image\""
+                  echo "\"status\": \"$safety\""
+          done < "$input"
