Updated scanner.yml

diff --git a/.github/workflows/scanner.yml b/.github/workflows/scanner.yml
--- a/.github/workflows/scanner.yml
+++ b/.github/workflows/scanner.yml
@@ -29,12 +29,18 @@ jobs:
 
       # TASK/TODO: 
       # Build this step in the workflow. Refer to the linked document in the README for more details
-      - name: Checkout repository
-        uses: actions/checkout@v3
-        with:
-          ref: main
-
       - name: TODO - Scan Vulnerabilities
         run: echo "Build this step in the workflow. Refer to the linked document in the README for more details"
         
-      - run: bash scan-images.sh
+      - run: |
+          echo "${{ github.event.issue.body }}" | tr -d "[]" | tr -s "," "\n" | tac > newscan.txt
+          input=newscan.txt
+
+          while IFS= read -r image
+          do
+              trivy image --security-checks vuln --quiet --format template --exit-code 1 "$image"
+              status=$(echo $?)
+              if [ "$status" -eq 0 ]; then safety="SAFE"; else safety="UNSAFE"; fi
+              echo "\"image\": \"$image\""
+              echo "\"status\": \"$safety\""
+          done < "$input"
