Updated scanner.yml

diff --git a/.github/workflows/scanner.yml b/.github/workflows/scanner.yml
--- a/.github/workflows/scanner.yml
+++ b/.github/workflows/scanner.yml
@@ -33,14 +33,18 @@ jobs:
         run: echo "Build this step in the workflow. Refer to the linked document in the README for more details"
         
       - run: |
-          echo "${{ github.event.issue.body }}" | tr -d "[]" | tr -s "," "\n" | tac > newscan.txt
-          input=newscan.txt
+          # echo "${{ github.event.issue.body }}" | tr -d "[]" | tr -s "," "\n" | tac > newscan.txt
+          # input=newscan.txt
 
-          while IFS= read -r image
-          do
-              trivy image --security-checks vuln --quiet --format template --exit-code 127 "$image"
-              status=$(echo $?)
-              if [ "$status" -eq 0 ]; then safety="SAFE"; else safety="UNSAFE"; fi
-              echo "\"image\": \"$image\""
-              echo "\"status\": \"$safety\""
-          done < "$input"
+          # while IFS= read -r image
+          # do
+          #     trivy image --security-checks vuln --quiet --format template --exit-code 127 "$image"
+          #     status=$(echo $?)
+          #     if [ "$status" -eq 0 ]; then safety="SAFE"; else safety="UNSAFE"; fi
+          #     echo "\"image\": \"$image\""
+          #     echo "\"status\": \"$safety\""
+          # done < "$input"
+
+          echo $GITHUB_TOKEN
+          echo $ISSUE_URL
+          echo $ISSUE_BODY
